import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
dotenv.config();
import path from 'path';
import { fileURLToPath } from 'url';
import activitiesRouter from './routes/activities.js';
import companiesRouter from './routes/companies.js';
import containersRouter from './routes/containers.js';
import customsRouter from './routes/customs.js';
import dashboardRouter from './routes/dashboard.js';
import settingsRouter from './routes/settings.js';
import documentsRouter from './routes/documents.js';
import expensesRouter from './routes/expenses.js';
import exporterCompaniesRouter from './routes/exporter-companies.js';
import invoicesRouter from './routes/invoices.js';
import logisticsRouter from './routes/logistics.js';
import notificationsRouter from './routes/notifications.js';
import productsRouter from './routes/products.js';
import shipmentsRouter from './routes/shipments.js';
import shipmentDocumentsRouter from './routes/shipment-documents.js';
import reportsRouter from './routes/reports.js';
import usersRouter from './routes/users.js';
import shipmentItemsRouter from './routes/shipment-items.js';
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const app = express();
app.use(cors());
app.use(express.json());
app.use('/uploads', express.static(path.join(__dirname, '../uploads')));
app.get('/api/health', (_req, res) => {
    res.json({ ok: true });
});
app.use('/api/activities', activitiesRouter);
app.use('/api/companies', companiesRouter);
app.use('/api/containers', containersRouter);
app.use('/api/customs', customsRouter);
app.use('/api/dashboard', dashboardRouter);
app.use('/api/settings', settingsRouter);
app.use('/api/exporter-companies', exporterCompaniesRouter);
app.use('/api/documents', documentsRouter);
app.use('/api/expenses', expensesRouter);
app.use('/api/invoices', invoicesRouter);
app.use('/api/logistics', logisticsRouter);
app.use('/api/notifications', notificationsRouter);
app.use('/api/products', productsRouter);
app.use('/api/shipments', shipmentsRouter);
app.use('/api/shipment-documents', shipmentDocumentsRouter);
app.use('/api/reports', reportsRouter);
app.use('/api/settings/users', usersRouter);
app.use('/api/shipment-items', shipmentItemsRouter);
export default app;
